name: cartoon_repository
description: A web archive of eastern and western political cartoons.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  url_launcher: ^6.0.3
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_swiper:
    git:
      url: https://github.com/markmusic2727/flutter_swiper
  cupertino_icons: ^1.0.2

dev_dependencies:
  mobx_codegen: ^2.0.1+3
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Square
      fonts:
        - asset: assets/fonts/font.ttf
