name: cartoon_repository
description: A web archive of eastern and western political cartoons.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_swiper:
    git:
      url: https://github.com/markmusic2727/flutter_swiper

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Square
      fonts:
        - asset: assets/fonts/font.ttf
